In [2]:
from seqdec.bandits import EpsilonGreedyBandit, UCBBandit
from seqdec.simulator import BernoulliSimulator

In [3]:
import numpy as np

In [4]:
K = 5

sim = BernoulliSimulator(K)
bandit = EpsilonGreedyBandit(epsilon=0.1, sim=sim)

In [5]:
bandit.run()

In [6]:
bandit.q

array([0.92820181, 0.265625  , 0.22751323, 0.22619048, 0.58285714])

In [7]:
sim.proba

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503])

In [8]:
bandit = UCBBandit(sim=sim)
bandit.run()

In [9]:
bandit.q

array([0.93028895, 0.08333333, 0.        , 0.08333333, 0.58823529])